export const GET_ROBOTS_REQUEST = 'GET_ROBOTS_REQUEST';
export const GET_ROBOTS_SUCCESS = 'GET_ROBOTS_SUCCESS';
export const GET_ROBOTS_FAILED = 'GET_ROBOTS_FAILED';

export const POST_EXTINGUISH_REQUEST = 'POST_EXTINGUISH_REQUEST';
export const POST_EXTINGUISH_SUCCESS = 'POST_EXTINGUISH_SUCCESS';
export const POST_EXTINGUISH_FAILED = 'POST_EXTINGUISH_FAILED';

export const POST_RECYCLE_REQUEST = 'POST_RECYCLE_REQUEST';
export const POST_RECYCLE_SUCCESS = 'POST_RECYCLE_SUCCESS';
export const POST_RECYCLE_FAILED = 'POST_RECYCLE_FAILED';

export const UPDATE_READY_TO_SHIP = 'UPDATE_READY_TO_SHIP';

export const PUT_SEND_SHIPMENT_REQUEST = 'PUT_SEND_SHIPMENT_REQUEST';
export const PUT_SEND_SHIPMENT_SUCCESS = 'PUT_SEND_SHIPMENT_SUCCESS';
export const PUT_SEND_SHIPMENT_FAILED = 'PUT_SEND_SHIPMENT_FAILED';
